

cc_test (
    name = "thread_safe_container_test",
    srcs = [
        "thread_safe_containter_test.cc",
    ],
    deps = [
        "@gtest//:gtest",
        "@gtest//:gtest_main", 
        "//src:thread_pool"
    ],
)

cc_test (
    name = "thread_pool_test",
    srcs = [
        "thread_pool_test.cc",
    ],
    deps = [
        "@gtest//:gtest",
        "@gtest//:gtest_main", 
        "//src:thread_pool"       
    ],
)

cc_test (
    name = "parallel_algo_test",
    srcs = [
        "parallel_algo_test.cc",
    ],
    deps = [
        "@gtest//:gtest",
        "@gtest//:gtest_main", 
        "//src:parallel_algo"  
    ],
)