cc_library(
    name = "thread_pool",
    hdrs = ["thread_pool.h"],
    deps = ["thread_safe_container"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "parallel_algo",
    hdrs = ["parallel_algo.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "thread_safe_container",
    hdrs = ["thread_safe_container.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "thread_wrapper",
    hdrs = ["thread_wrapper.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "string",
    hdrs = ["string.h"],
    visibility = ["//visibility:public"],
)